openapi: 3.0.3
info:
  title: Checkout.com - Identity Verification Address document verifications (Coming soon) Address document verifications (Coming soon) Service status API
  version: 1.0.0
  x-logo:
    url: https://raw.githubusercontent.com/ubbleai/docs/main/cko_doc_logo.png
  description: ''
servers:
- url: https://api.ubble.ai
tags:
- name: Service status
paths:
  /health:
    get:
      tags:
      - Service status
      summary: Retrieve API health
      description: This endpoint allows you to get the health of our api, anything other than a 200 status code is not OK
      operationId: retrieve_api_health
      responses:
        '200':
          description: API is OK
x-tagGroups:
- name: Endpoints documentation
  tags:
  - Applicants
  - Business applicants
  - Identity verifications
  - ID document verifications
  - Face authentications
  - AML verifications
  - Website verifications (Coming soon)
  - Bank document verifications (Coming soon)
  - Company document verifications (Coming soon)
  - Address document verifications (Coming soon)
  - Service status
